test(contract): replace external dependencies with mock
Informasjonsforvaltning/fdk-harvester-bff pull request #7
Opened 2020-09-25 12:02 UTC by rannveigskjerve

2020-09-25 12:33 UTC, NilsOveTen requested changes

2020-09-25 12:33 UTC, NilsOveTen commented on .flake8
> +ignore = ANN101,B009,E203,E501,W503,DAR101,DAR201,D100,D103,D107,D101,D104,BLK100
Ikke ignorer black, Kjør heller nox sesjonen for black, den fikser alt som feiler på BLK100 automatisk

2020-09-25 12:33 UTC, NilsOveTen commented on README.md
> +ORGANIZATION_CATALOGUE_BASE_URI=http://localhost:8081
Du kan fint fjerne HOST og HOST_PORT herfra

2020-09-30 12:08 UTC, stigbd approved these changes
Det @NilsOveTen  sa.

2020-12-02 14:11 UTC, NilsOveTen commented
Jeg fant en gammel pr fra rannveig, har rebaset og fikset mine egne kommentarer

2020-12-02 16:16 UTC, NilsOveTen approved these changes

2020-12-02 16:20 UTC, merged